Added documentation around system streams
kurrent-io/EventStore pull request #4710
Opened 2024-12-31 12:33 UTC by rmfaheem

Fixes https://github.com/EventStore/documentation/issues/762

2025-01-02 19:10 UTC, coloradomorrissey commented
Thanks for this update, Faheem. I noticed a few quick grammatical errors that should be corrected before we post.  

In the non-specific System Streams table: 
For the purpose of the $all stream, the second sentence needs to be cleaned up.   Should be:   _Events in the $all stream are ordered in the sequence they are written to the database._

In the Projection Streams table:
"Everytime" should be "Every time" (two words).

2025-01-03 07:46 UTC, rmfaheem commented
Nice catch. Thanks, I've updated the changes.

2025-01-08 15:25 UTC, coloradomorrissey submitted a review, later dismissed

2025-01-22 12:15 UTC, hayley-jean requested changes

2025-01-22 12:15 UTC, hayley-jean commented on docs/server/features/streams.md
> +| **`$users`**            | Record of users in the database. All events have the reserved type **`$User`**.
`$users` and `$users-{name}` streams will only be created if [Basic authentication](https://developers.eventstore.com/server/v24.10/security/user-authentication.html#basic-authentication) is enabled, and won't be created if using Insecure, LDAPS, or OAuth.

2025-01-22 12:15 UTC, hayley-jean commented on docs/server/features/streams.md
> +| **`$scavenges`**   | Records the results and states of scavenging operations. |
```suggestion
| **`$scavenges`** | Indexes all scavenge operations that have run on the cluster. |
| **`$scavenges-{scavengeId}`**   | Records the results and states of a specific scavenge operation. |
```

2025-03-28 15:43 UTC, hayley-jean approved these changes

2025-03-28 15:44 UTC, merged